## Vetores e Matrizes

In [5]:
import numpy as np
A=np.array([[5.90,7.10],[2.38,2.52],[2.90,2.00]])
B=4.10*A
print(B)

[[24.19  29.11 ]
 [ 9.758 10.332]
 [11.89   8.2  ]]


### Dados os vetores u=(3,-5,2) e v=(4,6,3), calcule u.v e uXv

In [6]:
import numpy as np
u=np.array([[3,-5,2]])
v=np.array([[4,6,3]])
uv=np.inner(u,v)
uXv=np.cross(u,v)
print(uv)
print(uXv)

[[-12]]
[[-27  -1  38]]


In [9]:
import numpy as np
u=np.array([[7,1,-9]])
v=np.array([[3,-5,-4]])
uv=np.inner(u,v)
uXv=np.cross(u,v)
print(uv)
print(uXv)

[[52]]
[[-49   1 -38]]


## Sistema Lineares

In [7]:
import numpy as np
A=np.array([[4,2,-1],[3,3,2],[0,5,2]])
b=np.array([[7],[20],[-1]])
x=np.linalg.solve(A,b)
print(x)

[[ 5.]
 [-3.]
 [ 7.]]


In [19]:
import numpy as np
A=np.array([[4,-3,1],[1,1,3],[2,3,-4]])
b=np.array([[15],[27],[31]])
x=np.linalg.solve(A,b)
print(x)

[[9.2345679 ]
 [8.35802469]
 [3.13580247]]


In [20]:
import numpy as np
A=np.array([[5,1,3],[-1,2,5],[4,-5,1]])
b=np.array([[76],[35],[22]])
x=np.linalg.solve(A,b)
print(x)

[[10.]
 [ 5.]
 [ 7.]]


In [12]:
A=np.array([[1,3,4],[2,-1,1],[-4,2,-2]])
b=np.array([[18],[10],[-7]])
x=np.linalg.solve(A,b)
print(x)

LinAlgError: Singular matrix

#### É UMA MATRIZ SINGULAR (NÃO TEM SOLUÇÃO)

In [14]:
import numpy as np
A=np.array([[10,120],[8,80]])
b=np.array([[844],[576]])
x=np.linalg.solve(A,b)
print(x)

[[10. ]
 [ 6.2]]


# Funções Trigonomêtricas

 ### Qual é o seno de 57° ?

In [18]:
import numpy as np
arco=np.deg2rad(57)
np.sin(arco)

0.838670567945424

### Qual é o ângulo cujo cosseno é igual a 0,7?

In [19]:
import numpy as np
angulo=np.arccos(0.7)
np.rad2deg(angulo)

45.5729959991943

# Números complexos 

#### Obs: separando raiz em duas 
Número Complexo na forma algébrica: z=a+bi
   a=parte real:
   a=Re(z)




b=parte imaginária:
   b=Im(z)

### Escreva o número complexo z=3+5j utilizando o Python

In [20]:
z=complex(3,5)
print(z)

(3+5j)


### Obtenha o módulo do número complexo z=3+5j

In [21]:
z=complex(3,5)
abs(z)

5.830951894845301

In [24]:
z1=complex(3,5)
z2=complex(7,-3)
soma=z1+z2
produto=z1*z2
divisao=z1/z2
print(soma)
print(produto)
print(divisao)

(10+2j)
(36+26j)
(0.10344827586206899+0.7586206896551725j)


# Sistemas Lineares com números complexos

In [2]:
import numpy as np
A=np.array([[complex(2,1),complex(5,-1)],[complex(5,1),complex(7,4)]])
b=np.array([[complex(3,8)],[complex(2,5)]])
np.linalg.solve(A,b)

array([[ 2.26819127-0.68607069j],
       [-0.7006237 +1.28066528j]])

In [3]:
import numpy as np
A=np.array([[complex(3,2),complex(-2,-6)],[complex(-2,-6),complex(10,1)]])
x1=np.cos(np.deg2rad(0))
y1=np.sin(np.deg2rad(0))
x2=np.cos(np.deg2rad(30))
y2=np.sin(np.deg2rad(30))
b=np.array([[70*complex(x1,y1)],[110*complex(x2,y2)]])
np.linalg.solve(A,b)

array([[9.13078549+12.6784592j ],
       [5.04631419+13.00953172j]])

In [18]:
import numpy as np
A=np.array([[complex(1,5),complex(3,-2)],[complex(3,-2),complex(4,1)]])
x1=np.cos(np.deg2rad(23))
y1=np.sin(np.deg2rad(37))
b=np.array([[30*complex(x1,y1)],[52*complex(x2,y2)]])
np.linalg.solve(A,b)

array([[2.62923451+3.29913765j],
       [9.3251167 +6.75312463j]])